package com.narenkg.hecko.consts;

public enum EMessage {
	Message,
	SIGNUP_USER_ALREADY_EXISTS,
	USER_NOT_FOUND,
	SIGNUP_USER_SUCCESS,
	SIGNUP_VENDOR_SUCCESS,
	SIGNIN_EMAIL_NOTVERIFIED,
	SIGNIN_ACCOUNT_BLOCKED,
	SIGNIN_USER_NOTFOUND,
	SIGNIN_SUCCESS,
	VENDOR_UPDATE_SERVICE_FAILED,
	VENDOR_UPDATE_SERVICE_SUCCESS,
	OTP_GENERATE_SUCCESS,
	OTP_GENERATE_FAILED,
	OTP_EXPIRED_OR_WRONG,
	TECHNICAL_ISSUE,
	GOOD_TO_GO,
	NOT_VALID_EMAIL_OR_MOBILENUMBER,
	PASSWORD_NOT_MATCHING,
	ROLE_UPDATE_SUCCESS
}
