export const GlobalCountries = {
  list: [
    {
      name: "Afghanistan",
      value: "+93",
      key: "AF",
      flag: require("../assets/images/countryflags/png/af.png"),
    },
    {
      name: "Aland Islands",
      value: "+358",
      key: "AX",
      flag: require("../assets/images/countryflags/png/ax.png"),
    },
    {
      name: "Albania",
      value: "+355",
      key: "AL",
      flag: require("../assets/images/countryflags/png/al.png"),
    },
    {
      name: "Algeria",
      value: "+213",
      key: "DZ",
      flag: require("../assets/images/countryflags/png/dz.png"),
    },
    {
      name: "American Samoa",
      value: "+1684",
      key: "AS",
      flag: require("../assets/images/countryflags/png/as.png"),
    },
    {
      name: "Andorra",
      value: "+376",
      key: "AD",
      flag: require("../assets/images/countryflags/png/ad.png"),
    },
    {
      name: "Angola",
      value: "+244",
      key: "AO",
      flag: require("../assets/images/countryflags/png/ao.png"),
    },
    {
      name: "Anguilla",
      value: "+1264",
      key: "AI",
      flag: require("../assets/images/countryflags/png/ai.png"),
    },
    {
      name: "Antarctica",
      value: "+672",
      key: "AQ",
      flag: require("../assets/images/countryflags/png/aq.png"),
    },
    {
      name: "Antigua and Barbuda",
      value: "+1268",
      key: "AG",
      flag: require("../assets/images/countryflags/png/ag.png"),
    },
    {
      name: "Argentina",
      value: "+54",
      key: "AR",
      flag: require("../assets/images/countryflags/png/ar.png"),
    },
    {
      name: "Armenia",
      value: "+374",
      key: "AM",
      flag: require("../assets/images/countryflags/png/am.png"),
    },
    {
      name: "Aruba",
      value: "+297",
      key: "AW",
      flag: require("../assets/images/countryflags/png/aw.png"),
    },
    {
      name: "Ascension Island",
      value: "+247",
      key: "AC",
      flag: require("../assets/images/countryflags/png/ac.png"),
    },
    {
      name: "Australia",
      value: "+61",
      key: "AU",
      flag: require("../assets/images/countryflags/png/au.png"),
    },
    {
      name: "Austria",
      value: "+43",
      key: "AT",
      flag: require("../assets/images/countryflags/png/at.png"),
    },
    {
      name: "Azerbaijan",
      value: "+994",
      key: "AZ",
      flag: require("../assets/images/countryflags/png/az.png"),
    },
    {
      name: "Bahamas",
      value: "+1242",
      key: "BS",
      flag: require("../assets/images/countryflags/png/bs.png"),
    },
    {
      name: "Bahrain",
      value: "+973",
      key: "BH",
      flag: require("../assets/images/countryflags/png/bh.png"),
    },
    {
      name: "Bangladesh",
      value: "+880",
      key: "BD",
      flag: require("../assets/images/countryflags/png/bd.png"),
    },
    {
      name: "Barbados",
      value: "+1246",
      key: "BB",
      flag: require("../assets/images/countryflags/png/bb.png"),
    },
    {
      name: "Belarus",
      value: "+375",
      key: "BY",
      flag: require("../assets/images/countryflags/png/by.png"),
    },
    {
      name: "Belgium",
      value: "+32",
      key: "BE",
      flag: require("../assets/images/countryflags/png/be.png"),
    },
    {
      name: "Belize",
      value: "+501",
      key: "BZ",
      flag: require("../assets/images/countryflags/png/bz.png"),
    },
    {
      name: "Benin",
      value: "+229",
      key: "BJ",
      flag: require("../assets/images/countryflags/png/bj.png"),
    },
    {
      name: "Bermuda",
      value: "+1441",
      key: "BM",
      flag: require("../assets/images/countryflags/png/bm.png"),
    },
    {
      name: "Bhutan",
      value: "+975",
      key: "BT",
      flag: require("../assets/images/countryflags/png/bt.png"),
    },
    {
      name: "Bolivia",
      value: "+591",
      key: "BO",
      flag: require("../assets/images/countryflags/png/bo.png"),
    },
    {
      name: "Bosnia and Herzegovina",
      value: "+387",
      key: "BA",
      flag: require("../assets/images/countryflags/png/ba.png"),
    },
    {
      name: "Botswana",
      value: "+267",
      key: "BW",
      flag: require("../assets/images/countryflags/png/bw.png"),
    },
    {
      name: "Brazil",
      value: "+55",
      key: "BR",
      flag: require("../assets/images/countryflags/png/br.png"),
    },
    {
      name: "British Indian Ocean Territory",
      value: "+246",
      key: "IO",
      flag: require("../assets/images/countryflags/png/io.png"),
    },
    {
      name: "Brunei Darussalam",
      value: "+673",
      key: "BN",
      flag: require("../assets/images/countryflags/png/bn.png"),
    },
    {
      name: "Bulgaria",
      value: "+359",
      key: "BG",
      flag: require("../assets/images/countryflags/png/bg.png"),
    },
    {
      name: "Burkina Faso",
      value: "+226",
      key: "BF",
      flag: require("../assets/images/countryflags/png/bf.png"),
    },
    {
      name: "Burundi",
      value: "+257",
      key: "BI",
      flag: require("../assets/images/countryflags/png/bi.png"),
    },
    {
      name: "Cambodia",
      value: "+855",
      key: "KH",
      flag: require("../assets/images/countryflags/png/kh.png"),
    },
    {
      name: "Cameroon",
      value: "+237",
      key: "CM",
      flag: require("../assets/images/countryflags/png/cm.png"),
    },
    {
      name: "Canada",
      value: "+1",
      key: "CA",
      flag: require("../assets/images/countryflags/png/ca.png"),
    },
    {
      name: "Cape Verde",
      value: "+238",
      key: "CV",
      flag: require("../assets/images/countryflags/png/cv.png"),
    },
    {
      name: "Cayman Islands",
      value: "+1345",
      key: "KY",
      flag: require("../assets/images/countryflags/png/ky.png"),
    },
    {
      name: "Central African Republic",
      value: "+236",
      key: "CF",
      flag: require("../assets/images/countryflags/png/cf.png"),
    },
    {
      name: "Chad",
      value: "+235",
      key: "TD",
      flag: require("../assets/images/countryflags/png/td.png"),
    },
    {
      name: "Chile",
      value: "+56",
      key: "CL",
      flag: require("../assets/images/countryflags/png/cl.png"),
    },
    {
      name: "China",
      value: "+86",
      key: "CN",
      flag: require("../assets/images/countryflags/png/cn.png"),
    },
    {
      name: "Christmas Island",
      value: "+61",
      key: "CX",
      flag: require("../assets/images/countryflags/png/cx.png"),
    },
    {
      name: "Cocos (Keeling) Islands",
      value: "+61",
      key: "CC",
      flag: require("../assets/images/countryflags/png/cc.png"),
    },
    {
      name: "Colombia",
      value: "+57",
      key: "CO",
      flag: require("../assets/images/countryflags/png/co.png"),
    },
    {
      name: "Comoros",
      value: "+269",
      key: "KM",
      flag: require("../assets/images/countryflags/png/km.png"),
    },
    {
      name: "Congo",
      value: "+242",
      key: "CG",
      flag: require("../assets/images/countryflags/png/cg.png"),
    },
    {
      name: "Cook Islands",
      value: "+682",
      key: "CK",
      flag: require("../assets/images/countryflags/png/ck.png"),
    },
    {
      name: "Costa Rica",
      value: "+506",
      key: "CR",
      flag: require("../assets/images/countryflags/png/cr.png"),
    },
    {
      name: "Croatia",
      value: "+385",
      key: "HR",
      flag: require("../assets/images/countryflags/png/hr.png"),
    },
    {
      name: "Cuba",
      value: "+53",
      key: "CU",
      flag: require("../assets/images/countryflags/png/cu.png"),
    },
    {
      name: "Cyprus",
      value: "+357",
      key: "CY",
      flag: require("../assets/images/countryflags/png/cy.png"),
    },
    {
      name: "Czech Republic",
      value: "+420",
      key: "CZ",
      flag: require("../assets/images/countryflags/png/cz.png"),
    },
    {
      name: "Democratic Republic of the Congo",
      value: "+243",
      key: "CD",
      flag: require("../assets/images/countryflags/png/cd.png"),
    },
    {
      name: "Denmark",
      value: "+45",
      key: "DK",
      flag: require("../assets/images/countryflags/png/dk.png"),
    },
    {
      name: "Djibouti",
      value: "+253",
      key: "DJ",
      flag: require("../assets/images/countryflags/png/dj.png"),
    },
    {
      name: "Dominica",
      value: "+1767",
      key: "DM",
      flag: require("../assets/images/countryflags/png/dm.png"),
    },
    {
      name: "Dominican Republic",
      value: "+1849",
      key: "DO",
      flag: require("../assets/images/countryflags/png/do.png"),
    },
    {
      name: "Ecuador",
      value: "+593",
      key: "EC",
      flag: require("../assets/images/countryflags/png/ec.png"),
    },
    {
      name: "Egypt",
      value: "+20",
      key: "EG",
      flag: require("../assets/images/countryflags/png/eg.png"),
    },
    {
      name: "El Salvador",
      value: "+503",
      key: "SV",
      flag: require("../assets/images/countryflags/png/sv.png"),
    },
    {
      name: "Equatorial Guinea",
      value: "+240",
      key: "GQ",
      flag: require("../assets/images/countryflags/png/gq.png"),
    },
    {
      name: "Eritrea",
      value: "+291",
      key: "ER",
      flag: require("../assets/images/countryflags/png/er.png"),
    },
    {
      name: "Estonia",
      value: "+372",
      key: "EE",
      flag: require("../assets/images/countryflags/png/ee.png"),
    },
    {
      name: "Eswatini",
      value: "+268",
      key: "SZ",
      flag: require("../assets/images/countryflags/png/sz.png"),
    },
    {
      name: "Ethiopia",
      value: "+251",
      key: "ET",
      flag: require("../assets/images/countryflags/png/et.png"),
    },
    {
      name: "Falkland Islands (Malvinas)",
      value: "+500",
      key: "FK",
      flag: require("../assets/images/countryflags/png/fk.png"),
    },
    {
      name: "Faroe Islands",
      value: "+298",
      key: "FO",
      flag: require("../assets/images/countryflags/png/fo.png"),
    },
    {
      name: "Fiji",
      value: "+679",
      key: "FJ",
      flag: require("../assets/images/countryflags/png/fj.png"),
    },
    {
      name: "Finland",
      value: "+358",
      key: "FI",
      flag: require("../assets/images/countryflags/png/fi.png"),
    },
    {
      name: "France",
      value: "+33",
      key: "FR",
      flag: require("../assets/images/countryflags/png/fr.png"),
    },
    {
      name: "French Guiana",
      value: "+594",
      key: "GF",
      flag: require("../assets/images/countryflags/png/gf.png"),
    },
    {
      name: "French Polynesia",
      value: "+689",
      key: "PF",
      flag: require("../assets/images/countryflags/png/pf.png"),
    },
    {
      name: "Gabon",
      value: "+241",
      key: "GA",
      flag: require("../assets/images/countryflags/png/ga.png"),
    },
    {
      name: "Gambia",
      value: "+220",
      key: "GM",
      flag: require("../assets/images/countryflags/png/gm.png"),
    },
    {
      name: "Georgia",
      value: "+995",
      key: "GE",
      flag: require("../assets/images/countryflags/png/ge.png"),
    },
    {
      name: "Germany",
      value: "+49",
      key: "DE",
      flag: require("../assets/images/countryflags/png/de.png"),
    },
    {
      name: "Ghana",
      value: "+233",
      key: "GH",
      flag: require("../assets/images/countryflags/png/gh.png"),
    },
    {
      name: "Gibraltar",
      value: "+350",
      key: "GI",
      flag: require("../assets/images/countryflags/png/gi.png"),
    },
    {
      name: "Greece",
      value: "+30",
      key: "GR",
      flag: require("../assets/images/countryflags/png/gr.png"),
    },
    {
      name: "Greenland",
      value: "+299",
      key: "GL",
      flag: require("../assets/images/countryflags/png/gl.png"),
    },
    {
      name: "Grenada",
      value: "+1473",
      key: "GD",
      flag: require("../assets/images/countryflags/png/gd.png"),
    },
    {
      name: "Guadeloupe",
      value: "+590",
      key: "GP",
      flag: require("../assets/images/countryflags/png/gp.png"),
    },
    {
      name: "Guam",
      value: "+1671",
      key: "GU",
      flag: require("../assets/images/countryflags/png/gu.png"),
    },
    {
      name: "Guatemala",
      value: "+502",
      key: "GT",
      flag: require("../assets/images/countryflags/png/gt.png"),
    },
    {
      name: "Guernsey",
      value: "+44-1481",
      key: "GG",
      flag: require("../assets/images/countryflags/png/gg.png"),
    },
    {
      name: "Guinea",
      value: "+224",
      key: "GN",
      flag: require("../assets/images/countryflags/png/gn.png"),
    },
    {
      name: "Guinea-Bissau",
      value: "+245",
      key: "GW",
      flag: require("../assets/images/countryflags/png/gw.png"),
    },
    {
      name: "Guyana",
      value: "+592",
      key: "GY",
      flag: require("../assets/images/countryflags/png/gy.png"),
    },
    {
      name: "Haiti",
      value: "+509",
      key: "HT",
      flag: require("../assets/images/countryflags/png/ht.png"),
    },
    {
      name: "Holy See (Vatican City State)",
      value: "+379",
      key: "VA",
      flag: require("../assets/images/countryflags/png/va.png"),
    },
    {
      name: "Honduras",
      value: "+504",
      key: "HN",
      flag: require("../assets/images/countryflags/png/hn.png"),
    },
    {
      name: "Hong Kong",
      value: "+852",
      key: "HK",
      flag: require("../assets/images/countryflags/png/hk.png"),
    },
    {
      name: "Hungary",
      value: "+36",
      key: "HU",
      flag: require("../assets/images/countryflags/png/hu.png"),
    },
    {
      name: "Iceland",
      value: "+354",
      key: "IS",
      flag: require("../assets/images/countryflags/png/is.png"),
    },
    {
      name: "India",
      value: "+91",
      key: "IN",
      flag: require("../assets/images/countryflags/png/in.png"),
    },
    {
      name: "Indonesia",
      value: "+62",
      key: "ID",
      flag: require("../assets/images/countryflags/png/id.png"),
    },
    {
      name: "Iran",
      value: "+98",
      key: "IR",
      flag: require("../assets/images/countryflags/png/ir.png"),
    },
    {
      name: "Iraq",
      value: "+964",
      key: "IQ",
      flag: require("../assets/images/countryflags/png/iq.png"),
    },
    {
      name: "Ireland",
      value: "+353",
      key: "IE",
      flag: require("../assets/images/countryflags/png/ie.png"),
    },
    {
      name: "Isle of Man",
      value: "+44-1624",
      key: "IM",
      flag: require("../assets/images/countryflags/png/im.png"),
    },
    {
      name: "Israel",
      value: "+972",
      key: "IL",
      flag: require("../assets/images/countryflags/png/il.png"),
    },
    {
      name: "Italy",
      value: "+39",
      key: "IT",
      flag: require("../assets/images/countryflags/png/it.png"),
    },
    {
      name: "Ivory Coast / Cote d'Ivoire",
      value: "+225",
      key: "CI",
      flag: require("../assets/images/countryflags/png/ci.png"),
    },
    {
      name: "Jamaica",
      value: "+1876",
      key: "JM",
      flag: require("../assets/images/countryflags/png/jm.png"),
    },
    {
      name: "Japan",
      value: "+81",
      key: "JP",
      flag: require("../assets/images/countryflags/png/jp.png"),
    },
    {
      name: "Jersey",
      value: "+44-1534",
      key: "JE",
      flag: require("../assets/images/countryflags/png/je.png"),
    },
    {
      name: "Jordan",
      value: "+962",
      key: "JO",
      flag: require("../assets/images/countryflags/png/jo.png"),
    },
    {
      name: "Kazakhstan",
      value: "+77",
      key: "KZ",
      flag: require("../assets/images/countryflags/png/kz.png"),
    },
    {
      name: "Kenya",
      value: "+254",
      key: "KE",
      flag: require("../assets/images/countryflags/png/ke.png"),
    },
    {
      name: "Kiribati",
      value: "+686",
      key: "KI",
      flag: require("../assets/images/countryflags/png/ki.png"),
    },
    {
      name: "Korea, Democratic People's Republic of Korea",
      value: "+850",
      key: "KP",
      flag: require("../assets/images/countryflags/png/kp.png"),
    },
    {
      name: "Korea, Republic of South Korea",
      value: "+82",
      key: "KR",
      flag: require("../assets/images/countryflags/png/kr.png"),
    },
    {
      name: "Kosovo",
      value: "+383",
      key: "XK",
      flag: require("../assets/images/countryflags/png/xk.png"),
    },
    {
      name: "Kuwait",
      value: "+965",
      key: "KW",
      flag: require("../assets/images/countryflags/png/kw.png"),
    },
    {
      name: "Kyrgyzstan",
      value: "+996",
      key: "KG",
      flag: require("../assets/images/countryflags/png/kg.png"),
    },
    {
      name: "Laos",
      value: "+856",
      key: "LA",
      flag: require("../assets/images/countryflags/png/la.png"),
    },
    {
      name: "Latvia",
      value: "+371",
      key: "LV",
      flag: require("../assets/images/countryflags/png/lv.png"),
    },
    {
      name: "Lebanon",
      value: "+961",
      key: "LB",
      flag: require("../assets/images/countryflags/png/lb.png"),
    },
    {
      name: "Lesotho",
      value: "+266",
      key: "LS",
      flag: require("../assets/images/countryflags/png/ls.png"),
    },
    {
      name: "Liberia",
      value: "+231",
      key: "LR",
      flag: require("../assets/images/countryflags/png/lr.png"),
    },
    {
      name: "Libya",
      value: "+218",
      key: "LY",
      flag: require("../assets/images/countryflags/png/ly.png"),
    },
    {
      name: "Liechtenstein",
      value: "+423",
      key: "LI",
      flag: require("../assets/images/countryflags/png/li.png"),
    },
    {
      name: "Lithuania",
      value: "+370",
      key: "LT",
      flag: require("../assets/images/countryflags/png/lt.png"),
    },
    {
      name: "Luxembourg",
      value: "+352",
      key: "LU",
      flag: require("../assets/images/countryflags/png/lu.png"),
    },
    {
      name: "Macau",
      value: "+853",
      key: "MO",
      flag: require("../assets/images/countryflags/png/mo.png"),
    },
    {
      name: "Madagascar",
      value: "+261",
      key: "MG",
      flag: require("../assets/images/countryflags/png/mg.png"),
    },
    {
      name: "Malawi",
      value: "+265",
      key: "MW",
      flag: require("../assets/images/countryflags/png/mw.png"),
    },
    {
      name: "Malaysia",
      value: "+60",
      key: "MY",
      flag: require("../assets/images/countryflags/png/my.png"),
    },
    {
      name: "Maldives",
      value: "+960",
      key: "MV",
      flag: require("../assets/images/countryflags/png/mv.png"),
    },
    {
      name: "Mali",
      value: "+223",
      key: "ML",
      flag: require("../assets/images/countryflags/png/ml.png"),
    },
    {
      name: "Malta",
      value: "+356",
      key: "MT",
      flag: require("../assets/images/countryflags/png/mt.png"),
    },
    {
      name: "Marshall Islands",
      value: "+692",
      key: "MH",
      flag: require("../assets/images/countryflags/png/mh.png"),
    },
    {
      name: "Martinique",
      value: "+596",
      key: "MQ",
      flag: require("../assets/images/countryflags/png/mq.png"),
    },
    {
      name: "Mauritania",
      value: "+222",
      key: "MR",
      flag: require("../assets/images/countryflags/png/mr.png"),
    },
    {
      name: "Mauritius",
      value: "+230",
      key: "MU",
      flag: require("../assets/images/countryflags/png/mu.png"),
    },
    {
      name: "Mayotte",
      value: "+262",
      key: "YT",
      flag: require("../assets/images/countryflags/png/yt.png"),
    },
    {
      name: "Mexico",
      value: "+52",
      key: "MX",
      flag: require("../assets/images/countryflags/png/mx.png"),
    },
    {
      name: "Micronesia, Federated States of Micronesia",
      value: "+691",
      key: "FM",
      flag: require("../assets/images/countryflags/png/fm.png"),
    },
    {
      name: "Moldova",
      value: "+373",
      key: "MD",
      flag: require("../assets/images/countryflags/png/md.png"),
    },
    {
      name: "Monaco",
      value: "+377",
      key: "MC",
      flag: require("../assets/images/countryflags/png/mc.png"),
    },
    {
      name: "Mongolia",
      value: "+976",
      key: "MN",
      flag: require("../assets/images/countryflags/png/mn.png"),
    },
    {
      name: "Montenegro",
      value: "+382",
      key: "ME",
      flag: require("../assets/images/countryflags/png/me.png"),
    },
    {
      name: "Montserrat",
      value: "+1664",
      key: "MS",
      flag: require("../assets/images/countryflags/png/ms.png"),
    },
    {
      name: "Morocco",
      value: "+212",
      key: "MA",
      flag: require("../assets/images/countryflags/png/ma.png"),
    },
    {
      name: "Mozambique",
      value: "+258",
      key: "MZ",
      flag: require("../assets/images/countryflags/png/mz.png"),
    },
    {
      name: "Myanmar",
      value: "+95",
      key: "MM",
      flag: require("../assets/images/countryflags/png/mm.png"),
    },
    {
      name: "Namibia",
      value: "+264",
      key: "NA",
      flag: require("../assets/images/countryflags/png/na.png"),
    },
    {
      name: "Nauru",
      value: "+674",
      key: "NR",
      flag: require("../assets/images/countryflags/png/nr.png"),
    },
    {
      name: "Nepal",
      value: "+977",
      key: "NP",
      flag: require("../assets/images/countryflags/png/np.png"),
    },
    {
      name: "Netherlands",
      value: "+31",
      key: "NL",
      flag: require("../assets/images/countryflags/png/nl.png"),
    },
    {
      name: "Netherlands Antilles",
      value: "+599",
      key: "AN",
      flag: require("../assets/images/countryflags/png/an.png"),
    },
    {
      name: "New Caledonia",
      value: "+687",
      key: "NC",
      flag: require("../assets/images/countryflags/png/nc.png"),
    },
    {
      name: "New Zealand",
      value: "+64",
      key: "NZ",
      flag: require("../assets/images/countryflags/png/nz.png"),
    },
    {
      name: "Nicaragua",
      value: "+505",
      key: "NI",
      flag: require("../assets/images/countryflags/png/ni.png"),
    },
    {
      name: "Niger",
      value: "+227",
      key: "NE",
      flag: require("../assets/images/countryflags/png/ne.png"),
    },
    {
      name: "Nigeria",
      value: "+234",
      key: "NG",
      flag: require("../assets/images/countryflags/png/ng.png"),
    },
    {
      name: "Niue",
      value: "+683",
      key: "NU",
      flag: require("../assets/images/countryflags/png/nu.png"),
    },
    {
      name: "Norfolk Island",
      value: "+672",
      key: "NF",
      flag: require("../assets/images/countryflags/png/nf.png"),
    },
    {
      name: "North Macedonia",
      value: "+389",
      key: "MK",
      flag: require("../assets/images/countryflags/png/mk.png"),
    },
    {
      name: "Northern Mariana Islands",
      value: "+1670",
      key: "MP",
      flag: require("../assets/images/countryflags/png/mp.png"),
    },
    {
      name: "Norway",
      value: "+47",
      key: "NO",
      flag: require("../assets/images/countryflags/png/no.png"),
    },
    {
      name: "Oman",
      value: "+968",
      key: "OM",
      flag: require("../assets/images/countryflags/png/om.png"),
    },
    {
      name: "Pakistan",
      value: "+92",
      key: "PK",
      flag: require("../assets/images/countryflags/png/pk.png"),
    },
    {
      name: "Palau",
      value: "+680",
      key: "PW",
      flag: require("../assets/images/countryflags/png/pw.png"),
    },
    {
      name: "Palestine",
      value: "+970",
      key: "PS",
      flag: require("../assets/images/countryflags/png/ps.png"),
    },
    {
      name: "Panama",
      value: "+507",
      key: "PA",
      flag: require("../assets/images/countryflags/png/pa.png"),
    },
    {
      name: "Papua New Guinea",
      value: "+675",
      key: "PG",
      flag: require("../assets/images/countryflags/png/pg.png"),
    },
    {
      name: "Paraguay",
      value: "+595",
      key: "PY",
      flag: require("../assets/images/countryflags/png/py.png"),
    },
    {
      name: "Peru",
      value: "+51",
      key: "PE",
      flag: require("../assets/images/countryflags/png/pe.png"),
    },
    {
      name: "Philippines",
      value: "+63",
      key: "PH",
      flag: require("../assets/images/countryflags/png/ph.png"),
    },
    {
      name: "Pitcairn",
      value: "+872",
      key: "PN",
      flag: require("../assets/images/countryflags/png/pn.png"),
    },
    {
      name: "Poland",
      value: "+48",
      key: "PL",
      flag: require("../assets/images/countryflags/png/pl.png"),
    },
    {
      name: "Portugal",
      value: "+351",
      key: "PT",
      flag: require("../assets/images/countryflags/png/pt.png"),
    },
    {
      name: "Puerto Rico",
      value: "+1939",
      key: "PR",
      flag: require("../assets/images/countryflags/png/pr.png"),
    },
    {
      name: "Qatar",
      value: "+974",
      key: "QA",
      flag: require("../assets/images/countryflags/png/qa.png"),
    },
    {
      name: "Reunion",
      value: "+262",
      key: "RE",
      flag: require("../assets/images/countryflags/png/re.png"),
    },
    {
      name: "Romania",
      value: "+40",
      key: "RO",
      flag: require("../assets/images/countryflags/png/ro.png"),
    },
    {
      name: "Russia",
      value: "+7",
      key: "RU",
      flag: require("../assets/images/countryflags/png/ru.png"),
    },
    {
      name: "Rwanda",
      value: "+250",
      key: "RW",
      flag: require("../assets/images/countryflags/png/rw.png"),
    },
    {
      name: "Saint Barthelemy",
      value: "+590",
      key: "BL",
      flag: require("../assets/images/countryflags/png/bl.png"),
    },
    {
      name: "Saint Helena, Ascension and Tristan Da Cunha",
      value: "+290",
      key: "SH",
      flag: require("../assets/images/countryflags/png/sh.png"),
    },
    {
      name: "Saint Kitts and Nevis",
      value: "+1869",
      key: "KN",
      flag: require("../assets/images/countryflags/png/kn.png"),
    },
    {
      name: "Saint Lucia",
      value: "+1758",
      key: "LC",
      flag: require("../assets/images/countryflags/png/lc.png"),
    },
    {
      name: "Saint Martin",
      value: "+590",
      key: "MF",
      flag: require("../assets/images/countryflags/png/mf.png"),
    },
    {
      name: "Saint Pierre and Miquelon",
      value: "+508",
      key: "PM",
      flag: require("../assets/images/countryflags/png/pm.png"),
    },
    {
      name: "Saint Vincent and the Grenadines",
      value: "+1784",
      key: "VC",
      flag: require("../assets/images/countryflags/png/vc.png"),
    },
    {
      name: "Samoa",
      value: "+685",
      key: "WS",
      flag: require("../assets/images/countryflags/png/ws.png"),
    },
    {
      name: "San Marino",
      value: "+378",
      key: "SM",
      flag: require("../assets/images/countryflags/png/sm.png"),
    },
    {
      name: "Sao Tome and Principe",
      value: "+239",
      key: "ST",
      flag: require("../assets/images/countryflags/png/st.png"),
    },
    {
      name: "Saudi Arabia",
      value: "+966",
      key: "SA",
      flag: require("../assets/images/countryflags/png/sa.png"),
    },
    {
      name: "Senegal",
      value: "+221",
      key: "SN",
      flag: require("../assets/images/countryflags/png/sn.png"),
    },
    {
      name: "Serbia",
      value: "+381",
      key: "RS",
      flag: require("../assets/images/countryflags/png/rs.png"),
    },
    {
      name: "Seychelles",
      value: "+248",
      key: "SC",
      flag: require("../assets/images/countryflags/png/sc.png"),
    },
    {
      name: "Sierra Leone",
      value: "+232",
      key: "SL",
      flag: require("../assets/images/countryflags/png/sl.png"),
    },
    {
      name: "Singapore",
      value: "+65",
      key: "SG",
      flag: require("../assets/images/countryflags/png/sg.png"),
    },
    {
      name: "Sint Maarten",
      value: "+1721",
      key: "SX",
      flag: require("../assets/images/countryflags/png/sx.png"),
    },
    {
      name: "Slovakia",
      value: "+421",
      key: "SK",
      flag: require("../assets/images/countryflags/png/sk.png"),
    },
    {
      name: "Slovenia",
      value: "+386",
      key: "SI",
      flag: require("../assets/images/countryflags/png/si.png"),
    },
    {
      name: "Solomon Islands",
      value: "+677",
      key: "SB",
      flag: require("../assets/images/countryflags/png/sb.png"),
    },
    {
      name: "Somalia",
      value: "+252",
      key: "SO",
      flag: require("../assets/images/countryflags/png/so.png"),
    },
    {
      name: "South Africa",
      value: "+27",
      key: "ZA",
      flag: require("../assets/images/countryflags/png/za.png"),
    },
    {
      name: "South Georgia and the South Sandwich Islands",
      value: "+500",
      key: "GS",
      flag: require("../assets/images/countryflags/png/gs.png"),
    },
    {
      name: "South Sudan",
      value: "+211",
      key: "SS",
      flag: require("../assets/images/countryflags/png/ss.png"),
    },
    {
      name: "Spain",
      value: "+34",
      key: "ES",
      flag: require("../assets/images/countryflags/png/es.png"),
    },
    {
      name: "Sri Lanka",
      value: "+94",
      key: "LK",
      flag: require("../assets/images/countryflags/png/lk.png"),
    },
    {
      name: "Sudan",
      value: "+249",
      key: "SD",
      flag: require("../assets/images/countryflags/png/sd.png"),
    },
    {
      name: "Suriname",
      value: "+597",
      key: "SR",
      flag: require("../assets/images/countryflags/png/sr.png"),
    },
    {
      name: "Svalbard and Jan Mayen",
      value: "+47",
      key: "SJ",
      flag: require("../assets/images/countryflags/png/sj.png"),
    },
    {
      name: "Sweden",
      value: "+46",
      key: "SE",
      flag: require("../assets/images/countryflags/png/se.png"),
    },
    {
      name: "Switzerland",
      value: "+41",
      key: "CH",
      flag: require("../assets/images/countryflags/png/ch.png"),
    },
    {
      name: "Syrian Arab Republic",
      value: "+963",
      key: "SY",
      flag: require("../assets/images/countryflags/png/sy.png"),
    },
    {
      name: "Taiwan",
      value: "+886",
      key: "TW",
      flag: require("../assets/images/countryflags/png/tw.png"),
    },
    {
      name: "Tajikistan",
      value: "+992",
      key: "TJ",
      flag: require("../assets/images/countryflags/png/tj.png"),
    },
    {
      name: "Tanzania, United Republic of Tanzania",
      value: "+255",
      key: "TZ",
      flag: require("../assets/images/countryflags/png/tz.png"),
    },
    {
      name: "Thailand",
      value: "+66",
      key: "TH",
      flag: require("../assets/images/countryflags/png/th.png"),
    },
    {
      name: "Timor-Leste",
      value: "+670",
      key: "TL",
      flag: require("../assets/images/countryflags/png/tl.png"),
    },
    {
      name: "Togo",
      value: "+228",
      key: "TG",
      flag: require("../assets/images/countryflags/png/tg.png"),
    },
    {
      name: "Tokelau",
      value: "+690",
      key: "TK",
      flag: require("../assets/images/countryflags/png/tk.png"),
    },
    {
      name: "Tonga",
      value: "+676",
      key: "TO",
      flag: require("../assets/images/countryflags/png/to.png"),
    },
    {
      name: "Trinidad and Tobago",
      value: "+1868",
      key: "TT",
      flag: require("../assets/images/countryflags/png/tt.png"),
    },
    {
      name: "Tunisia",
      value: "+216",
      key: "TN",
      flag: require("../assets/images/countryflags/png/tn.png"),
    },
    {
      name: "Turkey",
      value: "+90",
      key: "TR",
      flag: require("../assets/images/countryflags/png/tr.png"),
    },
    {
      name: "Turkmenistan",
      value: "+993",
      key: "TM",
      flag: require("../assets/images/countryflags/png/tm.png"),
    },
    {
      name: "Turks and Caicos Islands",
      value: "+1649",
      key: "TC",
      flag: require("../assets/images/countryflags/png/tc.png"),
    },
    {
      name: "Tuvalu",
      value: "+688",
      key: "TV",
      flag: require("../assets/images/countryflags/png/tv.png"),
    },
    {
      name: "Uganda",
      value: "+256",
      key: "UG",
      flag: require("../assets/images/countryflags/png/ug.png"),
    },
    {
      name: "Ukraine",
      value: "+380",
      key: "UA",
      flag: require("../assets/images/countryflags/png/ua.png"),
    },
    {
      name: "United Arab Emirates",
      value: "+971",
      key: "AE",
      flag: require("../assets/images/countryflags/png/ae.png"),
    },
    {
      name: "United Kingdom",
      value: "+44",
      key: "GB",
      flag: require("../assets/images/countryflags/png/gb.png"),
    },
    {
      name: "United States",
      value: "+1",
      key: "US",
      flag: require("../assets/images/countryflags/png/us.png"),
    },
    {
      name: "United States Minor Outlying Islands",
      value: "+246",
      key: "UMI",
      flag: require("../assets/images/countryflags/png/umi.png"),
    },
    {
      name: "Uruguay",
      value: "+598",
      key: "UY",
      flag: require("../assets/images/countryflags/png/uy.png"),
    },
    {
      name: "Uzbekistan",
      value: "+998",
      key: "UZ",
      flag: require("../assets/images/countryflags/png/uz.png"),
    },
    {
      name: "Vanuatu",
      value: "+678",
      key: "VU",
      flag: require("../assets/images/countryflags/png/vu.png"),
    },
    {
      name: "Venezuela, Bolivarian Republic of Venezuela",
      value: "+58",
      key: "VE",
      flag: require("../assets/images/countryflags/png/ve.png"),
    },
    {
      name: "Vietnam",
      value: "+84",
      key: "VN",
      flag: require("../assets/images/countryflags/png/vn.png"),
    },
    {
      name: "Virgin Islands, British",
      value: "+1284",
      key: "VG",
      flag: require("../assets/images/countryflags/png/vg.png"),
    },
    {
      name: "Virgin Islands, U.S.",
      value: "+1340",
      key: "VI",
      flag: require("../assets/images/countryflags/png/vi.png"),
    },
    {
      name: "Wallis and Futuna",
      value: "+681",
      key: "WF",
      flag: require("../assets/images/countryflags/png/wf.png"),
    },
    {
      name: "Yemen",
      value: "+967",
      key: "YE",
      flag: require("../assets/images/countryflags/png/ye.png"),
    },
    {
      name: "Zambia",
      value: "+260",
      key: "ZM",
      flag: require("../assets/images/countryflags/png/zm.png"),
    },
    {
      name: "Zimbabwe",
      value: "+263",
      key: "ZW",
      flag: require("../assets/images/countryflags/png/zw.png"),
    },
  ],
};
