export const GlobalSizes = {
  primaryButton: {
    radius: 20,
    borderWidth: 2,
    pressedOpacity: 0.6,
    paddingRight: 18,
    paddingLeft: 16,
    paddingVertical: 8,
  },
  orderView: {
    radius: 5,
    height: 100,
    width: "100%",
    progressBar: 5,
    percentageText: 11,
    titleFontSize: 14,
    NormalTextFont: 12,
    pickAndDropImg: 20,
  },
  searchText: {
    borderWidth: 1,
    borderRadius: 16,
    height: 50,
    marginHorizontal: 10,
    marginVertical: 10,
    marginRight: 12,
    borderRadius: 12,
    paddingHorizontal: 12,
  },
  vendorProfile:{
    paddingHorizontal:5,
    width:"100%",
    marginVertical: 8,
    paddingVertical: 4,
    borderWidth: 1,
    borderRadius: 7,
    height: 25,
    contactWidth:110,
    ContactpaddingVertical:2,
    bookingMarginVertical:4,
    bookingHeight:33,
  }
};
