export const GlobalSizes = {
  app: {
    padding: 8,
  },
  primaryButton: {
    radius: 20,
    borderWidth: 2,
    pressedOpacity: 0.6,
    paddingRight: 18,
    paddingLeft: 16,
    paddingVertical: 6,
  },
  orderView: {
    radius: 5,
    height: 100,
    width: "100%",
    progressBar: 5,
    percentageText: 11,
    titleFontSize: 14,
    NormalTextFont: 12,
    pickAndDropImg: 20,
  },
  searchText: {
    borderWidth: 1,
    height: 50,
    marginHorizontal: 6,
    marginVertical: 10,
    marginRight: 12,
    borderRadius: 4,
    paddingHorizontal: 12,
    padding: 4,
  },
  vendorProfile: {
    paddingHorizontal: 5,
    width: "100%",
    marginVertical: 8,
    paddingVertical: 4,
    borderWidth: 1,
    borderRadius: 7,
    height: 25,
    contactWidth: 110,
    ContactpaddingVertical: 2,
    bookingMarginVertical: 4,
    bookingHeight: 33,
  },
  input: {
    borderRadius: 4,
    borderWidth: 1,
    paddingRight: 10,
    paddingLeft: 10,
  },
};
