package com.narenkg.hecko.constants;

public enum EMessage {
	Message,
	SIGNUP_USER_ALREADY_EXISTS,
	USER_NOT_FOUND,
	SIGNUP_USER_SUCCESS,
	SIGNUP_VENDOR_SUCCESS,
	SIGNIN_EMAIL_NOTVERIFIED,
	SIGNIN_ACCOUNT_BLOCKED,
	SIGNIN_USER_NOTFOUND,
	SIGNIN_SUCCESS,
	VENDOR_UPDATE_SERVICE_FAILED,
	VENDOR_UPDATE_SERVICE_SUCCESS

}
