export const OTP_EXPIRED_OR_WRONG = "OTP_EXPIRED_OR_WRONG";
export const PASSWORD_NOT_MATCHING = "PASSWORD_NOT_MATCHING";
export const SIGNUP_EMAIL_ALREADY_REGISTERED =
  "SIGNUP_EMAIL_ALREADY_REGISTERED";
export const TECHNICAL_ISSUE = "TECHNICAL_ISSUE";
